export default {
  name: 'English',
  code: 'en',
  labels: {
    'date.format.message': 'Please follow mm/dd/yyyy format',
    'date.format': 'MM/DD/YYYY',
    'date.pattern': '\\d{2}/\\d{2}/\\d{4}',
    'gauge.background': 'Background color',
    'gauge.gradient.end': 'End color',
    'gauge.gradient.start': 'Start color',
    'gauge.value': 'Value',
    'iro.send': 'Send to Iro',
    'login.screen.accessPoints': 'Access Points',
    'login.screen.application.name': 'Join the iros ^_^',
    'login.screen.connect': 'Connect',
    'login.screen.create': 'New Iro',
    'login.screen.denied': 'Access denied',
    'login.screen.email': 'Email',
    'login.screen.expired': 'Session expired',
    'login.screen.login': 'User',
    'login.screen.password': 'Password',
    'main.language': 'Language',
    'menu.logout': 'Log out',
    'menu.greeting': 'Hello',
    'menu.home': 'Home',
    'wave.background': 'Background color',
    'wave.gradient.end': 'End color',
    'wave.gradient.start': 'Start color',
  },
};
