export default {
  name: 'English',
  code: 'en',
  labels: {
    'date.format.message': 'Please follow mm/dd/yyyy format',
    'date.format': 'MM/DD/YYYY',
    'date.pattern': '\\d{2}/\\d{2}/\\d{4}',
    'iro.send': 'Send to Iro',
    'login.screen.accessPoints': 'Access Points',
    'login.screen.application.name': 'Join the iros ^_^',
    'login.screen.connect': 'Connect',
    'login.screen.create': 'New Iro',
    'login.screen.denied': 'Access denied',
    'login.screen.email': 'Email',
    'login.screen.expired': 'Session expired',
    'login.screen.login': 'User',
    'login.screen.password': 'Password',
    'main.language': 'Language',
  },
};
