export default {
  name: 'Français',
  code: 'fr',
  labels: {
    'date.format.message': 'Date au format jj/mm/aaaa',
    'date.format': 'DD/MM/YYYY',
    'date.pattern': '\\d{2}/\\d{2}/\\d{4}',
    'iro.send': 'Envoyer à Iro',
    'login.screen.accessPoints': 'Points d\'accès',
    'login.screen.application.name': 'Rejoindre les iros ^_^',
    'login.screen.connect': 'Connexion',
    'login.screen.create': 'Nouveau Iro ?',
    'login.screen.denied': 'Accès refusé',
    'login.screen.email': 'Adresse électronique',
    'login.screen.expired': 'Session expirée',
    'login.screen.login': 'Utilisateur',
    'login.screen.password': 'Mot de passe',
    'main.language': 'Langue',
  },
};
