version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:80"
    links:
      - iro-mongo
    depends_on:
      - iro-mongo
  iro-mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /var/data:/data/db
    ports:
      - "27017:27017"
